apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aliyun-billing-exporter.fullname" . }}-config
data:
  REGION: "{{ .Values.env.region }}"
  START_MONTH: "{{ .Values.env.month }}"
  EXPORTER_PORT: "{{ .Values.service.port }}"
  ACCOUNT: "{{ .Values.env.account }}"
