apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aliyun-billing-exporter.fullname" . }}-secret
type: Opaque
data:
  ALIYUN_ACCESS_KEY: {{ .Values.secret.accessKey | b64enc }}
  ALIYUN_SECRET_KEY: {{ .Values.secret.secretKey | b64enc }}

